export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <h1>
          Bug with server actions blocking UI - {new Date().toISOString()}
        </h1>
        {children}
      </body>
    </html>
  );
}
